// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Course   string
	Student  string
	Subjects string
	Teacher  string
}{
	Course:   "course",
	Student:  "student",
	Subjects: "subjects",
	Teacher:  "teacher",
}
